# Generated by Django 4.2.16 on 2024-12-04 03:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30, verbose_name='Titulo Notificación')),
                ('imagen', models.ImageField(blank=True, default='notificaciones/noImagen.png', upload_to='notificaciones', verbose_name='Imagen')),
                ('contenido', models.TextField(max_length=200, verbose_name='Contenido de la notificación')),
                ('importante', models.BooleanField(default=False, verbose_name='Es una notificación importante')),
                ('creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificacion',
                'verbose_name_plural': 'Notificaciones',
            },
        ),
    ]
