# Generated by Django 5.1.3 on 2024-12-12 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
        ('promociones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30, verbose_name='Titulo Notificación')),
                ('imagen', models.ImageField(blank=True, default='notificaciones/noImagen.png', upload_to='notificacionesEspeciales', verbose_name='Imagen')),
                ('contenido', models.TextField(max_length=200, verbose_name='Contenido de la notificación')),
                ('creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promociones.promocion', verbose_name='Promoción vinculada')),
            ],
            options={
                'verbose_name': 'Notificacion (Especial)',
                'verbose_name_plural': 'Notificaciones (Especiales)',
            },
        ),
    ]
