# Generated by Django 5.1.3 on 2024-12-12 02:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre de la promoción')),
                ('imagen', models.ImageField(blank=True, default='promociones/default.jpg', upload_to='promociones', verbose_name='Imagen de la promoción')),
                ('precio', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio')),
                ('stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='el stock de la promoción no puede ser inferior a 0')])),
                ('creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Promocion',
                'verbose_name_plural': 'Promociones',
            },
        ),
    ]
